### ISSUE TITLE
新加问题

### ISSUE THREAD

**Issue by wowthewonderfulland** [eagleoflqj/p1a3_script#10]
【题目】 下面哪部作品是喜剧？
仲夏夜之梦

**Comment by society765** [comment]
【题目】 下面哪个童话故事不是安徒生写的？
  国王的新装
  卖火柴的小女孩
  冰雪女王
  尼尔斯骑鹅旅行记

**Comment by ghost** [comment]
【题目】 下面哪个童话故事不是安徒生写的？
国王的新装
卖火柴的小女孩
冰雪女王
尼尔斯骑鹅旅行记

**Comment by eagleoflqj** [comment]
Thank you two!
