### ISSUE TITLE
新题

### ISSUE THREAD

**Issue by haozihong** [eagleoflqj/p1a3_script#104]
关于地里积分类型“萝卜”的说法，哪些正确？
这些都对

**Comment by haozihong** [comment]
有的人征友条件也太苛刻了怎么办？
这些都包括，不然我们上哪里看可爱的小哥哥小姐姐呢？

**Comment by 94rain** [comment]
两个问题和答案似乎都已加入：

https://github.com/eagleoflqj/p1a3_script/blob/3d21f55e3a8bb8db578f131ae9ee08de9dc50bae/QA.js#L24

https://github.com/eagleoflqj/p1a3_script/blob/3d21f55e3a8bb8db578f131ae9ee08de9dc50bae/QA.js#L126

**Comment by haozihong** [comment]
那也许是我的script当时还没更新？总之加入了就好。

**Comment by eagleoflqj** [comment]
应该是浏览器缓存了QA.js
