### ISSUE TITLE
更新题库

### ISSUE THREAD

**Issue by YC-1412** [eagleoflqj/p1a3_script#108]
1. 一亩三分地发帖可以选择内容用hide进行隐藏。正确隐藏语法是：
**答案**：两人第一次华山论剑，争的是荣名与[hide=188]《九阴真经》[/hide]；
其他答案：
  现下第四次恶战，[hide188]才是各出全力[/hide]，再无半点留情。
  洪七公伸指疾点欧阳锋背心{hide=188}“凤尾穴”(/hide)，要迫他松手。
  第二次在桃花岛过招，是为了郭靖与[hide=188]欧阳克[\hide]争婚。

2. 为什么有时候一亩三分地的数据跟我感觉的平均情况相差很大？
**答案**： 这些都包括
其他答案：
  越极端的数据越引人注意
  越极端的数据越容易被公布
  发帖人自我选择来分享自己的数据，并没有自称自己代表了“平均”

3. 为什么我们不鼓励用谐音或者各种拐弯抹角的说法来指代公司或者学校名称？比如：“湾区某元音开头和结尾公司”
**答案**：写成这样子，别人看不懂，也搜不到。如果别人也这样写，你也看不懂、搜不到。信息没法分享和交流。
其他答案：
  不知道
  这样不好玩
  也许有什么顾虑吧

**Comment by eagleoflqj** [comment]
https://github.com/eagleoflqj/p1a3_script/commit/4f0392ce77c8017f29f44548d18727a3806a7a37
谢谢
