### ISSUE TITLE
答题

### ISSUE THREAD

**Issue by wowthewonderfulland** [eagleoflqj/p1a3_script#11]
下面哪个州，有state income tax on wages
North Dakota

**Comment by wowthewonderfulland** [comment]
我发现好想题目有细微变动，也许不要全字匹配搜索问题？有这题“下面哪个州，有state income tax”

**Comment by ghost** [comment]
【题目】 美国哪个州具有地中海气候？
  德克萨斯
  加利福尼亚
  佛罗里达
  华盛顿

**Comment by wowthewonderfulland** [comment]
上面那一题 答案加利福尼亚 
题主你自己找答案太累了，让开issue的人发答案吧，他们至少可以拍出一个错误选项的。你在readme里提一句或者开个通告。

**Comment by wowthewonderfulland** [comment]
【题目】 以下哪个美国城市不靠海？
亚特兰大

**Comment by wowthewonderfulland** [comment]
> 【题目】 美国哪个州具有地中海气候？
> 德克萨斯
> 加利福尼亚
> 佛罗里达
> 华盛顿

开issue把答案写一下，减轻一点维护的负担

**Comment by thekingofcity** [comment]
> 下面哪个州，有state income tax on wages
> North Dakota

遇到这题+1
ps: “下面哪个州，有state income tax” 这题和不存在的题不太一样吧?

**Comment by eagleoflqj** [comment]
> 我发现好想题目有细微变动，也许不要全字匹配搜索问题？有这题“下面哪个州，有state income tax”

我也很头疼 网站今天改题目 明天就有可能投毒 比如 下面哪个收税 a b c 以上都收 然后选a就gg了
要是真有一天投毒了 我就尽快把自动提交答题那步取消
我先把题目加上 反正我维护题库的成本不会超过网站维护题库的成本 要是模糊匹配的话可能在投毒前就自己判断错了

**Comment by eagleoflqj** [comment]
> 上面那一题 答案加利福尼亚
> 题主你自己找答案太累了，让开issue的人发答案吧，他们至少可以拍出一个错误选项的。你在readme里提一句或者开个通告。

哈哈哈 我倒没关系啦 我自己遇到新题拿不准的就往我在的新生群问去了
开源项目嘛 大家自愿贡献 不好要求太多 有人拿不准答案就不提issue了的话也是一种损失呢

**Comment by eagleoflqj** [comment]
谢谢大家
