### ISSUE TITLE
更新题库：如果不希望大家继续讨论我发表的帖子，应该如何操作？

### ISSUE THREAD

**Issue by 94rain** [eagleoflqj/p1a3_script#123]
【题目】 如果不希望大家继续讨论我发表的帖子，应该如何操作？
  私信管理组要求删帖
  帖子首楼右下角->”道具“中选择”关贴卡“，使用在自己发的主贴上。
  发帖子要求管理员删帖
  发工单要求删帖

正确答案："帖子首楼右下角->”道具“中选择”关贴卡“，使用在自己发的主贴上。"

**Comment by eagleoflqj** [comment]
谢谢 https://github.com/eagleoflqj/p1a3_script/commit/6c40ffb337df838545a6f90595ef5f188d9fd0cd
