### ISSUE TITLE
更新题库：关于编辑帖子的说法，哪些正确？

### ISSUE THREAD

**Issue by 94rain** [eagleoflqj/p1a3_script#126]
【题目】 关于编辑帖子的说法，哪些正确？
  超过 30 分钟后，可以用”补充“功能。
  用户无权编辑他人发帖
  这些都正确
  在发帖后的 30 分钟内可以编辑。

这些都正确

**Comment by eagleoflqj** [comment]
谢谢 https://github.com/eagleoflqj/p1a3_script/commit/6c40ffb337df838545a6f90595ef5f188d9fd0cd
