### ISSUE TITLE
下面哪个公司的streaming service不是会员subscription付费模式运营的？

### ISSUE THREAD

**Issue by Tony-Feng** [eagleoflqj/p1a3_script#13]
下面哪个公司的streaming service不是会员subscription付费模式运营的？
Tubi

顺便一问，以后这个repo还会保持更新吗？或者还是迁移到新的repo中？

**Comment by eagleoflqj** [comment]
谢谢！
本repo长期更新，如果有天我没有精力了会给其他开发者权限去维护
