### ISSUE TITLE
更新题库: 关于地里的违规警告，哪种说法是错误的？

### ISSUE THREAD

**Issue by LanceChuang** [eagleoflqj/p1a3_script#130]
有的违规行为没被警告，因此，我的违规行为也不会被警告。
        只要暂时没被警告，以后也不会被警告。
        只有收到三次以上警告才可能被禁言和封号。
        (O)这些都是错误的

**Comment by eagleoflqj** [comment]
谢谢 https://github.com/eagleoflqj/p1a3_script/commit/6c40ffb337df838545a6f90595ef5f188d9fd0cd
