### ISSUE TITLE
更新题库

### ISSUE THREAD

**Issue by 94rain** [eagleoflqj/p1a3_script#133]
【题目】我想对论坛提出反馈，哪些说法不正确？
"在哪个版块想到，就发在哪个版块，反正版务组会阅读每个帖子的。"
针对某个具体帖子的反馈可以点击举报，填写理由，得到版务组最快的处理
可以用论坛下方的“联系我们”，提交工单给管理员
可以发在农民公社版，版务组无法保证回复每个人，但是会定期阅读内容，做出相应调整。

**Comment by eagleoflqj** [comment]
谢谢
https://github.com/eagleoflqj/p1a3_script/commit/ce38edbe0412d31d862f151b596294517acdc2ee
