### ISSUE TITLE
有时候不会自动答题是咋回事呢，怎么才能让他自动选答案

### ISSUE THREAD

**Issue by wmkai** [eagleoflqj/p1a3_script#135]

**Comment by eagleoflqj** [comment]
可能是因为没有收录这题
也可能是因为刚收录但是你的浏览器缓存了旧版本，这时可以来https://github.com/eagleoflqj/p1a3_script/blob/master/QA.js 搜一下答案

**Comment by wmkai** [comment]
> 可能是因为没有收录这题
> 也可能是因为刚收录但是你的浏览器缓存了旧版本，这时可以来https://github.com/eagleoflqj/p1a3_script/blob/master/QA.js 搜一下答案

感谢回复，这个脚本签到完不会跳到答题页面，如果能修改一下自动增加这个功能就更棒了

**Comment by eagleoflqj** [comment]
答题是个弹窗，哪个页面都可以点开的；只是签到完的结果页有个自动跳转，如果在结果页点开答题弹窗根本来不及答题就跳转了，所以现在是等跳转完了再自动点开
