### ISSUE TITLE
New Daily Question

### ISSUE THREAD

**Issue by FleetingEcho** [eagleoflqj/p1a3_script#136]
新增问题:
【题目】关于论坛账号分享的说法，哪些正确?

 A.推荐朋友也注册账号，我们就可以相互加分了
 B.我先绑定我的微信天天攒积分，再解绑我的微信，再绑定朋友的微信，我们俩就都可以用了
 C.我和朋友共享账号密码就可以了
 D.这些都不对  **--正确答案**

【题目】 有的帖子感觉只适用于某些非主流群体，为什么我不能回帖说：“你不该在一亩三分地发这种帖子，没用的！”？
  A.以上这些都有道理。(正确答案)
  B.非主流不代表不存在，他们可以站出来表达自己的意见。
  C.每个人只能代表自己发言，代表不了整个论坛用户
  D.我没见过的事情，也可能真的存在呢！

-------------------------------------
{
  '有的帖子感觉只适用于某些非主流群体，为什么我不能回帖说：“你不该在一亩三分地发这种帖子，没用的！”？':'以上这些都有道理',
  '关于论坛账号分享的说法，哪些正确?':'这些都不对',
}

**Comment by eagleoflqj** [comment]
谢谢
a146d029ba4177f64f6f605e356ac913376f266a
