### ISSUE TITLE
【题目】 下面论坛规则，下面哪种说法是正确的？

### ISSUE THREAD

**Issue by 94rain** [eagleoflqj/p1a3_script#137]
【题目】 下面论坛规则，下面哪种说法是正确的？
  微信注册后，论坛用户就能给我的微信发消息了
  我可以把奇葩室友、朋友、npy、中介、商家的 Linkedin 或者其他个人信息放在论坛上进行网爆。
  有的版块发帖消耗积分。如果试图跨区发帖躲开限制，在帖子被挪到正确的版块后，仍可能会被扣分。
  绑定微信，签到和答题获得的积分即使解绑微信，也不会丢失

有的版块发帖消耗积分。如果试图跨区发帖躲开限制，在帖子被挪到正确的版块后，仍可能会被扣分。

**Comment by 94rain** [comment]
【题目】 一亩三分地里有哪些方面的干货信息？
  各公司工作情况、面试信息、薪资水平、职场发展。
  这些都有
  投资理财、购置房产
  美国大学各专业录取信息，留学途中遇到的问题

这些都有

**Comment by eagleoflqj** [comment]
谢谢
https://github.com/eagleoflqj/p1a3_script/commit/a9b2393d8a245438755cf76a15fcad0ddb8f1570
