### ISSUE TITLE
Daily Question update

### ISSUE THREAD

**Issue by FleetingEcho** [eagleoflqj/p1a3_script#138]
【题目】 关于 网络 Troll 的定义，下面哪些说法正确？
  A.Troll 的目的就是引起关注和互动，普通用户越与之互动，越是正中 troll 的下怀
  B.一亩三分地社区文明守则要求大家不要当troll，也不要与troll 互动： Don't troll. Don't feed trolls.
  C.以上都对  (正确答案)
  D.Troll 喜欢在网上挑起争端，煽动仇恨
  
  
  
  【题目】 新人积分不够。下面哪些做法正确？ (答案A)
  A.分享干货、签到答题、参加活动等，争取早日攒够积分。
  B.到处发帖抱怨积分不够、看不到，没准会有帮助呢。
  C.注册个小号，相互加分（嘿嘿，地里有后台系统检测哦）
  D.想各种办法绕开积分限制，比如要求楼主私下把信息发给我
  

【题目】 如何对贴主表达支持？(答案B)

 A.加分
 B.这些都可以
 C.回帖表达支持
 D.点赞

**Comment by eagleoflqj** [comment]
谢谢
https://github.com/eagleoflqj/p1a3_script/commit/538f40c74118029259734bc5b4d3347bc6c2e8cd

**Comment by AllenHong0525** [comment]
给力
