### ISSUE TITLE
贡献几道题

### ISSUE THREAD

**Issue by gzz2000** [eagleoflqj/p1a3_script#139]
自己也在攒题，刚刚发现这个项目居然还在更新，于是对了一下我这有这个项目里没有的题。
```
    '在Linkedin上求内推如何作死': '这些都会作死',
    '以下哪种不是Mods of dataflow?': 'tcp/ip',
    '下面哪些行为会被扣分': '这些都会被扣分',
    '哪些行为有可能被禁言和封号？': '购买了VIP通行证，作为付费用户，违反网站规则。',
    '谈判工资时，哪种做法有利于得到更大的包裹？': '精读工资谈判宝典：https://www.1point3acres.com/bbs/thread-286214-1-1.html 知己知彼，百战不殆',
```
看起来QA.js是按某种方法排好序的，不知道怎么排的所以没直接交PR。
给repo主点赞！
那个Mods of dataflow真的没有打错，确实有两道题，一道是Mods of dataflow一个是Modes of dataflow哈哈哈

**Comment by eagleoflqj** [comment]
自打网站上了recaptcha，基本只能更新题库了
其实是按照新pin华yin字典序来排的

**Comment by eagleoflqj** [comment]
谢谢 f95f12f56d0e7262ebf5c47b5631b72f0895c064
地里应该是根据用户反馈修改过一些题目表述，比如Mods那题最早是Mods，但后来把typo修掉后原版的就没有出现过（也可能是我签得不太勤，如果我再遇到就加上

**Comment by gzz2000** [comment]
👍原来如此
