### ISSUE TITLE
【题目】 如果希望找人一起打球，应该发在哪个版

### ISSUE THREAD

**Issue by johan456789** [eagleoflqj/p1a3_script#164]
![image](https://user-images.githubusercontent.com/14802181/183548077-4bedac31-8765-4775-a23e-5aed8d301270.png)

用這個issue紀錄一下錯誤答案。

答案已知不是：
- 兴趣爱好

**Comment by 94rain** [comment]
玩友募集？

**Comment by z2z23n0** [comment]
https://github.com/eagleoflqj/p1a3_script/pull/166
