### ISSUE TITLE
建议：自动签到功能

### ISSUE THREAD

**Issue by yuanxili1** [eagleoflqj/p1a3_script#171]
开发者您好，感谢您的项目！
我有一个小的意见，希望您酌情考虑。当我们从Google/或其他外部页面进入1p3a论坛特定页面时，脚本会自动调用自动签到功能，并且将原本的页面覆盖（无法返回）。请问是否可以让自动签到的页面的唤起 更改到新标签页？

**Comment by eagleoflqj** [comment]
甚是合理
30b6bf3719808b3b951f3bcc0ab6bafd27be3455 已修
