### ISSUE TITLE
Update answer

### ISSUE THREAD

**Issue by calisober** [eagleoflqj/p1a3_script#175]
![image](https://user-images.githubusercontent.com/122924761/236712446-7f595cb4-77b5-44d2-997f-3ffc93ea8372.png)

似乎问题和答案都有修改：
```
'给自己发的帖子添加到相关的热门话题，哪些说法是错误的？': '可能会被扣分，视情况，最多扣 10 分',
↓
'给自己发的帖子添加到无关的热门话题，哪些说法是正确的？': '可能被扣分，视情况，最多扣 10 分',
```

**Comment by eagleoflqj** [comment]
感谢
如果问题和答案都改了，那更像是加了个新题
b166900ce06c9da25349665e93cf83aaba112b8c 添加了
