### ISSUE TITLE
论坛更新了新的签到, 答题的UI

### ISSUE THREAD

**Issue by markchen1024** [eagleoflqj/p1a3_script#176]
![image](https://github.com/eagleoflqj/p1a3_script/assets/3313951/f3132e14-21fe-4d3a-a1c8-e520fe4359a5)
![image](https://github.com/eagleoflqj/p1a3_script/assets/3313951/d444f99f-1ffb-4c11-9810-49d820eef1a7)

**Comment by eagleoflqj** [comment]
已由 c745bb57cf69e7713e172aa379b3ef887e09ca96 修复
