### ISSUE TITLE
新加问题

### ISSUE THREAD

**Issue by eyanq** [eagleoflqj/p1a3_script#19]
【题目】 以下哪个说法正确？

- 一篇一作指的是有一篇第一作者的文章
- 地里常见的缩写SoP是指standard operating procedure
- TG成绩里的G指的是GPA
- 只要是领域大牛写的推荐信都叫强推

正确答案：一篇一作指的是有一篇第一作者的文章

**Comment by eagleoflqj** [comment]
谢谢！
