### ISSUE TITLE
下面哪个州，有state income tax on wages

### ISSUE THREAD

**Issue by Tony-Feng** [eagleoflqj/p1a3_script#28]
Mississippi

**Comment by eagleoflqj** [comment]
谢谢

**Comment by peter0083** [comment]
下面哪个州，有state income tax on wages？
North Dakota
Wyoming
South Dakota
Tennessee


answer: ***North Dakota***

**Comment by shurui91** [comment]
Alaska
Florida
Nevada
South Dakota
Texas
Washington
Wyoming
Tennessee
New Hampshire

跳过这几个即可 这几个是没有state income tax的
