### ISSUE TITLE
code update in greasy fork

### ISSUE THREAD

**Issue by Tony-Feng** [eagleoflqj/p1a3_script#3]
Hello,

Could you please update the code in greasy fork? The previous code in: 
https://greasyfork.org/en/scripts/381792-1p3a-script/code
seems to be not updated.

Thanks in advance.

**Comment by eagleoflqj** [comment]
OK, I nearly forget I posted it to greasyfork. I did that for making this script more widely known.
Since I can't remember to update greasyfork every time I push a new version to github, you can also follow the instructions in README.md to get the latest version.

**Comment by Tony-Feng** [comment]
Thank you for your reply and your helpful script! By the way, it seems that the following question is not added in the question list, could you please check for that?

【题目】 下面哪家公司的总部不在西雅图
波音

Thank you~

**Comment by eagleoflqj** [comment]
Added. Thank for your contribution!
BTW I noticed greasyfork provided a function called `Source Syncing`. I set it to automatically sync script from github. I think it solved your problem, although latency is inevitable.

**Comment by Tony-Feng** [comment]
It is great we can have such a tool, latency is not a problem at all~
Thank you and I will continue to follow up.
