### ISSUE TITLE
Failed to work

### ISSUE THREAD

**Issue by hongbo-miao** [eagleoflqj/p1a3_script#41]
请问这个脚本还可以用吗？谢谢
我按照推荐的自动方法装了以后，并不能自动答题和签到。

我看到类似错误 https://github.com/eagleoflqj/p1a3_script/issues/6
在 Console 里运行 `jQuery.cookie('signed');`，显示错误：

> Uncaught ReferenceError: jQuery is not defined

![image](https://user-images.githubusercontent.com/3375461/74258330-1c320d80-4d31-11ea-92ba-bd4291990abb.png)

**Comment by eagleoflqj** [comment]
因为安全原因cookie已被弃用了。看一下油猴图标右下角有没有1（表示当前有脚本运行），以及设置功能是否能正确隐藏首页模块？虽然我这一直能用，但确实不时有人反映签到答题不正常（有的后来莫名其妙就好了）。

**Comment by hongbo-miao** [comment]
有呢，在运行
![image](https://user-images.githubusercontent.com/3375461/74260219-15f16080-4d34-11ea-9e21-d57aa04d0d61.png)

**Comment by hongbo-miao** [comment]
我稍微 debug 了下，好像是有些页面不行，因为网站载入速度过慢导致脚本先运行。所以收到

> 'onclick' of undefined

我试了下主页 https://www.1point3acres.com/bbs/ 签到和答题都可以了。谢谢啦！

**Comment by eagleoflqj** [comment]
也谢谢你提供的信息！

**Comment by hongbo-miao** [comment]
哦 不客气 : )

**Comment by Hongbo-Miao** [comment]
@eagleoflqj 嗯 这个网页我发现不行
https://www.1point3acres.com/bbs/forum-47-1.html

还有可能是这个页面结构不同，没有找到“按照你代码检索的元素”。你有空可以 debug 下。

**Comment by hongbo-miao** [comment]
@eagleoflqj 嗯 这个网页我发现不行
https://www.1point3acres.com/bbs/forum-47-1.html

还有种可能是这个页面结构不同，没有找到“按照你代码检索的元素”。你有空可以 debug 下。

**Comment by eagleoflqj** [comment]
页面结构看起来是一样的，是我没匹配这种url。
当时是因为个人主页结构不一样，就把签到答题限制在了论坛主页（以为大家都是从主页进去的，没做需求调研）。

**Comment by hongbo-miao** [comment]
Nice，0.8.5 版可以了，谢谢！
