### ISSUE TITLE
自動檢查答案正確性

### ISSUE THREAD

**Issue by johan456789** [eagleoflqj/p1a3_script#51]
最近一直有答錯的情形，回答之前忘記截圖，所以不記得題目是什麼了。

不知道有沒有可能自動檢查回答後的答題結果，如果有答錯的情況要把那題的答案在資料庫裡面排除。

**Comment by johan456789** [comment]
https://github.com/eagleoflqj/p1a3_script/pull/54#issue-401240890 這個可能是其中一個錯誤答案。

**Comment by harryge00** [comment]
@eagleoflqj 脚本能后台定期执行吗

**Comment by johan456789** [comment]
剛剛答錯了這題。這題怎麼會是錯的？

![screenshot](https://user-images.githubusercontent.com/14802181/80936918-a1473300-8e05-11ea-8dd8-3dee03d41037.png)
