### ISSUE TITLE
油猴导入脚本

### ISSUE THREAD

**Issue by 0guanhua0** [eagleoflqj/p1a3_script#57]
请问是不是得有 user.js 这个文件才会触发自动导入呢

**Comment by eagleoflqj** [comment]
没有听说过这个文件 按README说明导入即可

**Comment by 0guanhua0** [comment]
tampermonkey/greasemonkey  在遇到后缀名为 .user.js 的文件时会自动跳入到安装页面的

如果把p1a3_script.js 命名成 p1a3_script.user.js 会更加方便（e.g. https://github.com/moderntribe/tampermonkey-scripts/tree/master/github)

我开个PR 吧

**Comment by eagleoflqj** [comment]
> tampermonkey/greasemonkey 在遇到后缀名为 .user.js 的文件时会自动跳入到安装页面的
> 
> 如果把p1a3_script.js 命名成 p1a3_script.user.js 会更加方便（e.g. https://github.com/moderntribe/tampermonkey-scripts/tree/master/github)
> 
> 我开个PR 吧

这会影响现有的用户 不会被merge的
