### ISSUE TITLE
我装了这个插件不自动签到也不自动答题

### ISSUE THREAD

**Issue by 7878k** [eagleoflqj/p1a3_script#6]
用的是你推荐的方法装的 结果并没有自动。。

**Comment by eagleoflqj** [comment]
需要你提供足够的信息来定位问题
首先确认你的一亩三分地主页右上角的签到和答题按钮都在，而且可以成功手动签到or答题
然后确认你的油猴插件开启，且1p3a_script脚本开启
再试试刷新一亩三分地主页（当然如果你今天已经手动签到or答题了就只能明天试了）
如果你的积分足够，可以去录取汇报版试试自动查看三维的功能是否正常运行

**Comment by 7878k** [comment]
今天看打开页面自动答题了，但是没有自动签到

**Comment by eagleoflqj** [comment]
> 今天看打开页面自动答题了，但是没有自动签到

请在未自动签到也未手动签到时F12打开console，执行
jQuery.cookie('signed');
告诉我结果，以及此时页面右上角的签到按钮是否存在
