### ISSUE TITLE
It doesn't work recently

### ISSUE THREAD

**Issue by xun6000** [eagleoflqj/p1a3_script#64]

**Comment by eagleoflqj** [comment]
Please be more specific.

**Comment by xun6000** [comment]
recently, when I login the 1p3a website to check in, the script don't help to auto fill in anymore.

**Comment by xun6000** [comment]
does yours still work?

**Comment by eagleoflqj** [comment]
> does yours still work?

Yes. Are you enabling AdBlock Plus? That may be the issue.

**Comment by xun6000** [comment]
No. disable adblock plus don't help
