### ISSUE TITLE
隐藏“开通 VIP”时首页顶部自动切换的新闻也会被隐藏

### ISSUE THREAD

**Issue by samar1tan** [eagleoflqj/p1a3_script#69]
感谢您开发这一实用工具！

`0.8.9` 版本下隐藏“开通 VIP”时，首页顶部自动切换的新闻也会被隐藏，如图：
隐藏前：
![image](https://user-images.githubusercontent.com/30967204/109406315-f8c91780-79b2-11eb-885a-7e0f05599fac.png)
隐藏后：
![image](https://user-images.githubusercontent.com/30967204/109406323-02527f80-79b3-11eb-90f2-d7206644da86.png)

猜测可能与 21 年 2 月 UI 改版有关？

**Comment by eagleoflqj** [comment]
这个功能只是为了简单地隐藏对自己来说多余的模块；如果有人想看那些新闻，完全可以取消这一项勾选，相信顶栏留着“开通VIP”的字眼也没什么不妥
我用了ABP，中间的新闻都被自动隐藏了

**Comment by samar1tan** [comment]
明白了，谢谢！

Liumeo <notifications@github.com> 于2021年2月28日周日 上午11:34写道：
