### ISSUE TITLE
签到后跳转导致无法再自动打开答题并勾选正确选项

### ISSUE THREAD

**Issue by 94rain** [eagleoflqj/p1a3_script#72]
**版本**：` 0.8.12`

**浏览器UA**: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36`

**问题**：签到后，可以自动打开答题并勾选正确选项，
![image](https://user-images.githubusercontent.com/21193371/114967121-71722d80-9ea6-11eb-9c72-16ef6f6b3b0c.png)

但在输入验证码之前会很快跳转到签到结果的页面，此时不会再自动打开答题并勾选正确选项
![image](https://user-images.githubusercontent.com/21193371/114967283-bdbd6d80-9ea6-11eb-82c8-64b2bd11e820.png)

**可能的解决方案**:  在签到之后，先主动跳转到[签到结果页面](https://www.1point3acres.com/bbs/plugin.php?id=dsu_paulsign:sign)再答题；或者改变顺序，先答题再签到

**Comment by eagleoflqj** [comment]
谢谢，已修复https://github.com/eagleoflqj/p1a3_script/commit/5e7e12867b9c233672db732ba26d708b2cc58f8f
