### ISSUE TITLE
新题+答案

### ISSUE THREAD

**Issue by haozihong** [eagleoflqj/p1a3_script#73]
在一亩三分地论坛参与社区讨论需要遵守哪些规则？
这些全都要遵守

**Comment by wjm** [comment]
"遇到跟自己不同的意见怎么办？": "保持开放包容的心态，看看对方内容是否有可取之处。实在不喜欢就叉掉页面看点别的。"

补充一个

**Comment by eagleoflqj** [comment]
https://github.com/eagleoflqj/p1a3_script/commit/b6cf6269146b8ab3595f78ab664df3ceb3a001ae
多谢
