### ISSUE TITLE
关于帖子内容审核，哪种说法是正确的

### ISSUE THREAD

**Issue by Tony-Feng** [eagleoflqj/p1a3_script#75]
Q: 关于帖子内容审核，哪种说法是正确的
A: 下面关于论坛使用的说法，哪种是错误的

Options:
- 为系统触发，针对发言内容而不针对发言人。系统审核触发后，由管理者人工审核。
- 多级审核机制，去除了海量普通用户见不到的垃圾，广告内容。
- 下面关于论坛使用的说法，哪种是错误的
- 如果没有违规内容，大部分情况下，当天就会完成审核。最迟24-48小时内完成。

我感觉很奇怪，感觉这个正确选项是typo，不过确实是对的

**Comment by eagleoflqj** [comment]
看不太懂，等论坛更新吧

**Comment by Tony-Feng** [comment]
好的，那就暂时看论坛怎么说，不然这个答案很奇怪

**Comment by 94rain** [comment]
![image](https://user-images.githubusercontent.com/21193371/126111054-56e161e0-e9c7-455a-87c5-7271c13e00cc.png)
我碰到了，应该是修正了：
"关于帖子内容审核，哪种说法是正确的"
正确选项为 "这些都正确。"
