### ISSUE TITLE
如何建设性的讨论有争议的话题？

### ISSUE THREAD

**Issue by sgyzetrov** [eagleoflqj/p1a3_script#77]
"
如何建设性的讨论有争议的话题？
{这些办法轮流来}
"

**Comment by eagleoflqj** [comment]
https://github.com/eagleoflqj/p1a3_script/commit/fb2e139328d04c7654823e45f35e19c8cd4211b0
谢谢

**Comment by sgyzetrov** [comment]
客气，感觉最近题库更新了，连续几天都是新题
