### ISSUE TITLE
更新题库

### ISSUE THREAD

**Issue by StevenQu** [eagleoflqj/p1a3_script#81]
question: 如何说服论坛里意见不同的用户改变 TA 的意见？
answers: {'2': '骂TA，怼TA，让对方服输为止', '4': '带着亲友团和马甲一起上，说到对方改变为止。', '1': '从因特网存在开始，就不存在能被别人说服的用户。改变只能来源于自身。', '3': '摆事实讲道理，直到对方心悦诚服，亲口承认为止'}

**Comment by 94rain** [comment]
该问题已更新 #76

**Comment by eagleoflqj** [comment]
这个版本多一个句号，暂时不知道哪个正确

**Comment by DebuAqua** [comment]
【题目】 如何说服论坛里意见不同的用户改变 TA 的意见？
 带着亲友团和马甲一起上，说到对方改变为止。
 骂TA，怼TA，让对方服输为止
 从因特网存在开始，就不存在能被别人说服的用户。改变只能来源于自身。
 摆事实讲道理，直到对方心悦诚服，亲口承认为止

正确答案：  从因特网存在开始，就不存在能被别人说服的用户。改变只能来源于自身。

**Comment by eagleoflqj** [comment]
那就先更新为有句号的版本

**Comment by eagleoflqj** [comment]
谢谢 https://github.com/eagleoflqj/p1a3_script/commit/6c40ffb337df838545a6f90595ef5f188d9fd0cd
