### ISSUE TITLE
更新题库

### ISSUE THREAD

**Issue by CHC383** [eagleoflqj/p1a3_script#86]
问题: 有的人征友条件也太苛刻了怎么办？
答案: 这些都包括，不然我们上哪里看可爱的小哥哥小姐姐呢？

其余答案:
- 我不符合对方的要求，我换个页面、看看其他的小哥哥小姐姐。
- 尽管我觉得难度很大，但对方有权寻找心仪的那个人和承受找不到的结果。我送上祝福吧。
- 征友标准是非常个人的事情，不需要接受大众的标准。如果我们不喜欢别人言语尖酸、评头品足，我们也不要对别人言语尖酸、评头品足。

**Comment by eagleoflqj** [comment]
#93 
谢谢
